# -*- coding: utf-8 -*-
"""概念树的分类骨架与种子概念。

分类（CONCEPT_CATEGORIES）沿用旧系统 WSC3D `knowledge/categories.json` 的两级体系：
人 / 天然 / 人造 / 想象 / 纹样 / 故事·典故与图像题材 / 题刻 / 形态特征 / 行为 / 人物间关系 / 复合要素。
分类是固定骨架（代码常量），概念（concepts 表）挂在末级分类下，可在界面中随时新增。

种子概念（SEED_CONCEPTS）来自三处：
- 旧系统 knowledge/concepts.json 的 30 个概念；
- 标注 SOP 附录 A 的受控母题表（学界共识母题，附格套要点作说明）；
- 武梁祠西壁释文（蒋英炬、吴文祺）中出现的人物、物象、榜题名。
仅在库中不存在同名概念时插入，重启不会覆盖人工修改。
"""
from __future__ import annotations

# (id, name, parent_id)
CONCEPT_CATEGORIES: list[tuple[str, str, str | None]] = [
    ("cat-person", "人", None),
    ("cat-person-figure", "具体人物", "cat-person"),
    ("cat-person-role", "社会身份", "cat-person"),
    ("cat-person-body", "身体与形态", "cat-person"),
    ("cat-person-kinship", "亲属称谓", "cat-person"),
    ("cat-nature", "天然", None),
    ("cat-nature-animal", "动物", "cat-nature"),
    ("cat-nature-plant", "植物", "cat-nature"),
    ("cat-nature-sky", "天象与气象", "cat-nature"),
    ("cat-nature-terrain", "山川地物", "cat-nature"),
    ("cat-artifact", "人造", None),
    ("cat-artifact-weapon", "兵器武备", "cat-artifact"),
    ("cat-artifact-vehicle", "车与舟船", "cat-artifact"),
    ("cat-artifact-architecture", "建筑与构件", "cat-artifact"),
    ("cat-artifact-furniture", "家具陈设", "cat-artifact"),
    ("cat-artifact-daily", "日常用品", "cat-artifact"),
    ("cat-artifact-clothing", "服饰冠带", "cat-artifact"),
    ("cat-artifact-tool", "生产工具", "cat-artifact"),
    ("cat-artifact-ritual", "礼仪器物", "cat-artifact"),
    ("cat-artifact-other", "其他人造物", "cat-artifact"),
    ("cat-imagination", "想象", None),
    ("cat-imagination-deity", "神祇仙人", "cat-imagination"),
    ("cat-imagination-beast", "神兽瑞兽", "cat-imagination"),
    ("cat-imagination-realm", "仙境异域", "cat-imagination"),
    ("cat-imagination-other", "其他想象", "cat-imagination"),
    ("cat-pattern", "纹样", None),
    ("cat-pattern-geometric", "几何纹样", "cat-pattern"),
    ("cat-pattern-cloud", "云气纹样", "cat-pattern"),
    ("cat-pattern-biotic", "动植物纹样", "cat-pattern"),
    ("cat-pattern-other", "其他纹样", "cat-pattern"),
    ("cat-story", "故事、典故与图像题材", None),
    ("cat-story-assassin", "刺客故事", "cat-story"),
    ("cat-story-filial", "孝子故事", "cat-story"),
    ("cat-story-women", "列女故事", "cat-story"),
    ("cat-story-ruler", "帝王圣贤", "cat-story"),
    ("cat-story-loyal", "忠臣义士", "cat-story"),
    ("cat-story-theme", "图像主题", "cat-story"),
    ("cat-story-other", "其他故事", "cat-story"),
    ("cat-inscription", "题刻", None),
    ("cat-inscription-bangti", "榜题", "cat-inscription"),
    ("cat-inscription-jinian", "纪年题记", "cat-inscription"),
    ("cat-inscription-songming", "颂铭", "cat-inscription"),
    ("cat-inscription-other", "其他题刻", "cat-inscription"),
    ("cat-morphology", "形态特征", None),
    ("cat-morphology-whole", "整体形态", "cat-morphology"),
    ("cat-morphology-part", "局部形态", "cat-morphology"),
    ("cat-morphology-appearance", "外观特征", "cat-morphology"),
    ("cat-morphology-expression", "表达形式", "cat-morphology"),
    ("cat-morphology-appendage", "附加形态", "cat-morphology"),
    ("cat-behavior", "行为", None),
    ("cat-behavior-ritual", "仪式行为", "cat-behavior"),
    ("cat-behavior-travel", "出行行为", "cat-behavior"),
    ("cat-behavior-combat", "战斗行为", "cat-behavior"),
    ("cat-behavior-labor", "劳作行为", "cat-behavior"),
    ("cat-behavior-daily", "日常行为", "cat-behavior"),
    ("cat-relation", "人物间关系", None),
    ("cat-relation-kinship", "亲属关系", "cat-relation"),
    ("cat-relation-social", "君臣宾主", "cat-relation"),
    ("cat-relation-other", "其他关系", "cat-relation"),
    ("cat-composite", "复合要素", None),
    ("cat-composite-expression", "复合表达", "cat-composite"),
]

CATEGORY_IDS = {c[0] for c in CONCEPT_CATEGORIES}


def _c(name: str, category: str, aliases: str = "", desc: str = "") -> dict:
    return {"name": name, "category_id": category,
            "aliases": [a for a in aliases.split("|") if a], "description": desc}


SEED_CONCEPTS: list[dict] = [
    # ---------------- 想象 · 神祇仙人
    _c("西王母", "cat-imagination-deity", "金母", "戴玉胜、坐龙虎座或昆仑山，左右羽人、九尾狐、三足乌、捣药玉兔、蟾蜍侍奉；汉画绝对主角。"),
    _c("东王公", "cat-imagination-deity", "东王父", "与西王母对偶的男性主神。"),
    _c("伏羲", "cat-imagination-deity", "伏戏", "人首蛇身，持矩，常配日轮；汉画榜题多作“伏戏”。"),
    _c("女娲", "cat-imagination-deity", "", "人首蛇身，持规，常配月轮。"),
    _c("羽人", "cat-imagination-deity", "仙人", "双翼、飞举姿态，常侍奉西王母或引路升仙。"),
    _c("人首鸟身神", "cat-imagination-deity", "人首鸟身", "人首鸟身的神人，多见于西王母仙界画面。"),
    _c("有翼侍女", "cat-imagination-deity", "有翼仙女", "西王母两侧双肩有翼的侍女。"),
    _c("嫦娥", "cat-imagination-deity"),
    _c("雷公", "cat-imagination-deity", "", "击连鼓、旋绕雷车。"),
    _c("风伯", "cat-imagination-deity"),
    _c("雨师", "cat-imagination-deity"),
    _c("河伯", "cat-imagination-deity", "", "鱼车、水中乘龙。"),
    _c("太一帝君", "cat-imagination-deity"),
    # ---------------- 想象 · 神兽瑞兽
    _c("龙", "cat-imagination-beast"),
    _c("翼龙", "cat-imagination-beast", "应龙", "有翼之龙。"),
    _c("凤", "cat-imagination-beast", "凤鸟"),
    _c("青龙", "cat-imagination-beast"),
    _c("白虎", "cat-imagination-beast"),
    _c("朱雀", "cat-imagination-beast"),
    _c("玄武", "cat-imagination-beast", "", "龟蛇相缠。"),
    _c("麒麟", "cat-imagination-beast"),
    _c("九尾狐", "cat-imagination-beast", "", "西王母伴侣。"),
    _c("三足乌", "cat-imagination-beast", "阳乌", "日轮中的乌或单飞。"),
    _c("玉兔", "cat-imagination-beast", "捣药玉兔", "月轮中或西王母侧，捣药。"),
    _c("蟾蜍", "cat-imagination-beast", "", "月轮中或西王母侧。"),
    _c("飞廉", "cat-imagination-beast", "", "鸟首鹿身。"),
    _c("辟邪", "cat-imagination-beast", "天禄", "翼狮。"),
    # ---------------- 人 · 具体人物
    _c("祝融", "cat-person-figure", "祝诵氏", "三皇五帝列像之一，汉画榜题作“祝诵氏”。"),
    _c("神农", "cat-person-figure", "神农氏", "三皇五帝列像之一，常执耒耜。"),
    _c("黄帝", "cat-person-figure", "", "三皇五帝列像之一，戴冕。"),
    _c("颛顼", "cat-person-figure", "帝颛顼|高阳", "三皇五帝列像之一。"),
    _c("帝喾", "cat-person-figure", "帝俈|高辛", "三皇五帝列像之一，汉画榜题作“帝俈”。"),
    _c("尧", "cat-person-figure", "帝尧|放勋", "三皇五帝列像之一。"),
    _c("舜", "cat-person-figure", "帝舜|重华|虞舜", "三皇五帝列像之一。"),
    _c("禹", "cat-person-figure", "夏禹|大禹", "戴笠冠、执耜的治水形象。"),
    _c("夏桀", "cat-person-figure", "桀", "暴君形象：荷戟，坐人形御床。"),
    _c("丁兰", "cat-person-figure", "", "孝子，刻木为父。"),
    _c("老莱子", "cat-person-figure", "", "孝子，作婴儿之态娱亲。"),
    _c("莱子父", "cat-person-figure", "老莱子父"),
    _c("莱子母", "cat-person-figure", "老莱子母"),
    _c("闵子骞", "cat-person-figure", "闵损|子骞", "孝子，御车失棰。"),
    _c("子骞父", "cat-person-figure", "闵子骞父"),
    _c("子骞后母弟", "cat-person-figure", "闵子骞后母弟"),
    _c("曾母", "cat-person-figure", "慈母", "曾参之母，投杼下机。"),
    _c("曾参", "cat-person-figure", "曾子", "孝子，曾母投杼故事中跪于母前。"),
    _c("荆轲", "cat-person-figure", "", "刺秦王的刺客，格套中怒发奔向中柱。"),
    _c("秦王", "cat-person-figure", "秦王政|秦始皇", "荆轲刺秦王格套中绕柱惊避的一方。"),
    _c("秦武阳", "cat-person-figure", "秦舞阳", "荆轲的副使，格套中伏地。"),
    _c("樊於期", "cat-person-figure", "樊於其", "以匣中首级形象出现，汉画榜题作“樊於其”。"),
    _c("专诸", "cat-person-figure", "", "鱼腹藏剑刺吴王僚的刺客。"),
    _c("吴王僚", "cat-person-figure", "吴王|王僚", "专诸刺吴王故事中的被刺者。"),
    _c("齐桓公", "cat-person-figure", "桓公|小白", "曹子劫桓故事中被劫持的一方。"),
    _c("管仲", "cat-person-figure", "", "齐桓公之相，常侍立桓公身侧。"),
    _c("曹沫", "cat-person-figure", "曹子|曹刿", "持匕首劫齐桓公的鲁国将领，汉画榜题作“曹子”。"),
    _c("鲁庄公", "cat-person-figure", "", "曹子劫桓故事中在旁劝止的一方。"),
    _c("孔子", "cat-person-figure"),
    _c("老子", "cat-person-figure"),
    _c("周公", "cat-person-figure"),
    _c("成王", "cat-person-figure", "周成王"),
    _c("董永", "cat-person-figure"),
    _c("伯瑜", "cat-person-figure", "柏榆"),
    _c("邢渠", "cat-person-figure"),
    _c("金日磾", "cat-person-figure"),
    _c("楚昭贞姜", "cat-person-figure", "贞姜"),
    _c("鲁义姑姊", "cat-person-figure"),
    _c("秋胡妻", "cat-person-figure", "鲁秋洁妇"),
    _c("梁高行", "cat-person-figure"),
    # ---------------- 人 · 社会身份
    _c("侍女", "cat-person-role"),
    _c("侍者", "cat-person-role"),
    _c("侍郎", "cat-person-role", "", "持戟侍卫，专诸刺吴王格套中夹持刺客的二人。"),
    _c("使者", "cat-person-role"),
    _c("骑吏", "cat-person-role", "骑者|骑从"),
    _c("御者", "cat-person-role"),
    _c("步卒", "cat-person-role", "", "车骑出行队列中的步行随从。"),
    _c("乐工", "cat-person-role"),
    _c("舞者", "cat-person-role"),
    _c("童子", "cat-person-role", "小儿|婴儿"),
    _c("妇人", "cat-person-role", "妇"),
    _c("老人", "cat-person-role", "翁"),
    _c("神人", "cat-person-role", "", "释文中泛指的神人。"),
    _c("帝王", "cat-person-role"),
    # ---------------- 天然
    _c("马", "cat-nature-animal"),
    _c("鸟", "cat-nature-animal"),
    _c("犬", "cat-nature-animal", "狗"),
    _c("鱼", "cat-nature-animal"),
    _c("牛", "cat-nature-animal"),
    _c("羊", "cat-nature-animal"),
    _c("鹿", "cat-nature-animal"),
    _c("虎", "cat-nature-animal"),
    _c("猴", "cat-nature-animal"),
    _c("鸡", "cat-nature-animal"),
    _c("树", "cat-nature-plant"),
    _c("桑树", "cat-nature-plant"),
    _c("桂树", "cat-nature-plant"),
    _c("扶桑树", "cat-nature-plant"),
    _c("日轮", "cat-nature-sky", "日", "圆轮，内有阳乌。"),
    _c("月轮", "cat-nature-sky", "月", "圆轮，内有蟾蜍、桂树或玉兔。"),
    _c("北斗", "cat-nature-sky"),
    _c("星宿", "cat-nature-sky"),
    _c("山", "cat-nature-terrain", "山峦"),
    _c("江水", "cat-nature-terrain", "水"),
    # ---------------- 人造
    _c("匕首", "cat-artifact-weapon"),
    _c("剑", "cat-artifact-weapon"),
    _c("戟", "cat-artifact-weapon", "长戟"),
    _c("长刀", "cat-artifact-weapon"),
    _c("弓", "cat-artifact-weapon", "弓箭"),
    _c("兵器", "cat-artifact-weapon"),
    _c("箧", "cat-artifact-daily", "匣|盒", "匣、箧；刺客故事中常盛首级。"),
    _c("轺车", "cat-artifact-vehicle"),
    _c("軿车", "cat-artifact-vehicle"),
    _c("卷棚车", "cat-artifact-vehicle"),
    _c("辎车", "cat-artifact-vehicle"),
    _c("安车", "cat-artifact-vehicle"),
    _c("马车", "cat-artifact-vehicle", "车"),
    _c("船", "cat-artifact-vehicle"),
    _c("屋宇", "cat-artifact-architecture", "屋"),
    _c("楼阁", "cat-artifact-architecture"),
    _c("双阙", "cat-artifact-architecture"),
    _c("单阙", "cat-artifact-architecture"),
    _c("柱", "cat-artifact-architecture", "", "殿柱；荆轲刺秦王格套中央的中柱。"),
    _c("帷幔", "cat-artifact-architecture", "帷"),
    _c("横栏", "cat-artifact-architecture"),
    _c("榻", "cat-artifact-furniture", "床"),
    _c("案", "cat-artifact-furniture"),
    _c("几", "cat-artifact-furniture"),
    _c("雕座", "cat-artifact-furniture", "座"),
    _c("便面", "cat-artifact-daily", "扇"),
    _c("伞", "cat-artifact-daily", "华盖|伞盖"),
    _c("杼", "cat-artifact-daily"),
    _c("织机", "cat-artifact-tool"),
    _c("耒耜", "cat-artifact-tool", "耜|耒"),
    _c("锄", "cat-artifact-tool"),
    _c("犁", "cat-artifact-tool"),
    _c("矩", "cat-artifact-tool", "", "伏羲所执。"),
    _c("规", "cat-artifact-tool", "", "女娲所执。"),
    _c("珠果", "cat-artifact-daily", "", "仙界侍女手捧之物。"),
    _c("鼎", "cat-artifact-ritual"),
    _c("博山炉", "cat-artifact-ritual"),
    _c("樽", "cat-artifact-daily"),
    _c("镜", "cat-artifact-daily"),
    _c("灯", "cat-artifact-daily"),
    _c("乐器", "cat-artifact-daily"),
    _c("节", "cat-artifact-ritual", "持节"),
    _c("笏", "cat-artifact-ritual"),
    _c("璧", "cat-artifact-ritual"),
    _c("木像", "cat-artifact-other", "木人", "丁兰刻木为父之木像。"),
    _c("进贤冠", "cat-artifact-clothing", "斜顶进贤冠"),
    _c("冕", "cat-artifact-clothing"),
    _c("笠冠", "cat-artifact-clothing", "笠"),
    _c("高髻", "cat-artifact-clothing", "三环高髻"),
    _c("笄", "cat-artifact-clothing"),
    _c("玉胜", "cat-artifact-clothing"),
    _c("冠有翅", "cat-artifact-clothing", "双翅冠"),
    # ---------------- 纹样
    _c("双菱纹", "cat-pattern-geometric"),
    _c("菱形纹", "cat-pattern-geometric"),
    _c("连弧纹", "cat-pattern-geometric"),
    _c("几何纹", "cat-pattern-geometric"),
    _c("锯齿纹", "cat-pattern-geometric"),
    _c("绹纹", "cat-pattern-geometric", "绞索纹|绚纹"),
    _c("垂幔纹", "cat-pattern-geometric"),
    _c("卷云纹", "cat-pattern-cloud"),
    _c("云气纹", "cat-pattern-cloud"),
    _c("鸟首云纹", "cat-pattern-cloud"),
    _c("卷草纹", "cat-pattern-biotic"),
    _c("兽面纹", "cat-pattern-biotic"),
    # ---------------- 故事 · 刺客
    _c("荆轲刺秦王", "cat-story-assassin", "", "最常见格套：中柱（上插匕首）+ 荆轲与秦王分置两侧 + 秦舞阳 + 樊於期人头匣。武氏祠三幅、沂南、乐山、陕北、海宁均见。"),
    _c("专诸刺吴王", "cat-story-assassin", "专诸刺王僚", "鱼腹藏剑，王僚被刺。"),
    _c("曹子劫桓", "cat-story-assassin", "曹沫劫齐桓公", "曹沫劫齐桓公，鲁庄公在侧。"),
    _c("要离刺庆忌", "cat-story-assassin", "", "江上船，要离持剑，庆忌挥拳。"),
    _c("豫让刺赵襄子", "cat-story-assassin", "", "桥下伏击，赵襄子车马。"),
    _c("聂政刺韩王", "cat-story-assassin", "", "鼓琴入殿、自剥面皮。"),
    _c("二桃杀三士", "cat-story-assassin", "", "豆 + 三桃 + 三勇士 + 齐景公/晏子。"),
    _c("蔺相如完璧归赵", "cat-story-assassin", "", "秦王 + 柱 + 蔺相如举璧。"),
    _c("范雎受袍", "cat-story-assassin", "范雎释魏须贾"),
    _c("管仲射小白", "cat-story-assassin"),
    # ---------------- 故事 · 孝子
    _c("丁兰刻木事亲", "cat-story-filial", "丁兰刻木", "木刻人形 + 丁兰拱手 + 妻子（部分版本）。"),
    _c("老莱子娱亲", "cat-story-filial", "老莱子", "父母坐床榻 + 老莱子跌倒装婴儿啼 + 妻子端果盘。"),
    _c("闵子骞御车失棰", "cat-story-filial", "闵子骞失棰|芦衣顺母", "闵子骞驾车，棰跌落，父发现继母虐待。"),
    _c("曾母投杼", "cat-story-filial", "曾参啮指", "织机 + 三人传讹 + 曾母投杼下机。"),
    _c("董永侍父", "cat-story-filial", "", "树 + 推车（父亲在车上 + 鸠杖）+ 董永持锄回望。"),
    _c("伯瑜悲亲", "cat-story-filial", "柏榆伤亲", "成年伯瑜跪地掩面而泣 + 持杖佝偻母亲。"),
    _c("邢渠哺父", "cat-story-filial", "", "邢渠跪坐前倾，持筷喂父。"),
    _c("赵徇哺父", "cat-story-filial"),
    _c("金日磾拜母", "cat-story-filial", "", "屋宇内胡人女性 + 金日磾跪拜。"),
    _c("郭巨埋儿", "cat-story-filial", "埋儿奉母"),
    _c("朱明孝行", "cat-story-filial"),
    _c("孝乌", "cat-story-filial", "", "反哺老乌。"),
    _c("魏汤护亲", "cat-story-filial"),
    _c("三州孝人", "cat-story-filial"),
    _c("羊公孝行", "cat-story-filial"),
    _c("李善抚孤", "cat-story-filial"),
    _c("孝孙原毂", "cat-story-filial", "原谷"),
    # ---------------- 故事 · 列女
    _c("楚昭贞姜故事", "cat-story-women", "楚昭贞姜", "屋宇内贞姜端坐 + 屋外侍女执便面 + 江水。"),
    _c("鲁义姑姊故事", "cat-story-women", "鲁义姑姊", "妇人怀抱小儿右奔回首 + 童子 + 齐将军车马。"),
    _c("秋胡妻故事", "cat-story-women", "秋胡戏妻|鲁秋洁妇", "桑树 + 筐 + 采桑妇回首 + 秋胡持囊。"),
    _c("梁高行故事", "cat-story-women", "梁高行", "帷幔 + 妇人持镜持刀 + 持节使者 + 奉金者。"),
    _c("齐义继母", "cat-story-women"),
    _c("京师节女", "cat-story-women"),
    _c("梁节姑姊", "cat-story-women"),
    _c("齐桓卫姬", "cat-story-women"),
    _c("齐管妾婧", "cat-story-women"),
    _c("钟离春自荐", "cat-story-women"),
    _c("贞夫韩朋", "cat-story-women"),
    _c("杞梁妻", "cat-story-women"),
    _c("罗敷采桑", "cat-story-women"),
    _c("曹娥投江", "cat-story-women"),
    _c("七女为父报仇", "cat-story-women"),
    # ---------------- 故事 · 帝王圣贤
    _c("三皇五帝", "cat-story-ruler", "远古帝王", "远古帝王列像：伏羲女娲、祝融、神农、黄帝、颛顼、帝喾、尧、舜、禹，或殿以夏桀。"),
    _c("伏羲女娲交尾", "cat-story-ruler", "伏羲女娲", "人首蛇身、蛇尾相交，中间常有小儿。"),
    _c("孔子见老子", "cat-story-ruler", "", "二人相对作揖，常带小儿项橐。"),
    _c("周公辅成王", "cat-story-ruler", "", "中央小孩（成王）头上有华盖，两旁各立一人或数人。"),
    _c("秦始皇泗水捞鼎", "cat-story-ruler", "泗水捞鼎"),
    # ---------------- 故事 · 忠臣义士
    _c("信陵君迎侯嬴", "cat-story-loyal"),
    _c("苏武牧羊", "cat-story-loyal"),
    _c("伯夷叔齐", "cat-story-loyal"),
    _c("赵氏孤儿", "cat-story-loyal"),
    _c("季札挂剑", "cat-story-loyal"),
    _c("鸿门宴", "cat-story-loyal"),
    _c("王陵母伏剑", "cat-story-loyal"),
    _c("申生愚孝", "cat-story-loyal"),
    # ---------------- 故事 · 图像主题
    _c("西王母仙界", "cat-story-theme", "西王母仙境|昆仑仙界", "西王母端坐，羽人、翼龙、有翼侍女、捣药玉兔、蟾蜍环侍；多在山墙锐顶。"),
    _c("车骑出行", "cat-story-theme", "车马出行|车骑仪仗"),
    _c("宴饮", "cat-story-theme"),
    _c("狩猎", "cat-story-theme", "田猎"),
    _c("神仙会", "cat-story-theme"),
    _c("历史故事", "cat-story-theme"),
    _c("庖厨", "cat-story-theme"),
    _c("六博", "cat-story-theme"),
    _c("乐舞百戏", "cat-story-theme"),
    _c("水陆攻战", "cat-story-theme"),
    _c("胡汉战争", "cat-story-theme"),
    _c("谒见", "cat-story-theme"),
    _c("讲经", "cat-story-theme"),
    _c("献俘", "cat-story-theme"),
    _c("牛耕", "cat-story-theme"),
    _c("纺织", "cat-story-theme"),
    _c("采桑", "cat-story-theme"),
    _c("舂米", "cat-story-theme"),
    # ---------------- 题刻
    _c("人物榜题", "cat-inscription-bangti", "", "标注画面人物身份，如“秦王”“荆轲”“管仲”。"),
    _c("故事榜题", "cat-inscription-bangti", "赞辞榜题", "叙述故事或颂赞的多字榜题。"),
    _c("无字榜", "cat-inscription-bangti", "空榜|榜无题", "预留而未刻字的榜。"),
    _c("纪年题记", "cat-inscription-jinian"),
    _c("颂铭", "cat-inscription-songming", "赞辞"),
    # ---------------- 形态 / 行为
    _c("人身蛇尾", "cat-morphology-appendage", "人首蛇身"),
    _c("双肩有翼", "cat-morphology-appendage", "有翼|双翼"),
    _c("鸟身", "cat-morphology-appendage"),
    _c("怒发直竖", "cat-morphology-appearance"),
    _c("戴冕", "cat-morphology-appearance"),
    _c("戴冠", "cat-morphology-appearance"),
    _c("残泐", "cat-morphology-whole", "泐|残", "因风化残损而模糊的部位。"),
    _c("拱手", "cat-behavior-ritual"),
    _c("跽跪", "cat-behavior-ritual", "跪"),
    _c("拜", "cat-behavior-ritual"),
    _c("端坐", "cat-behavior-daily", "坐"),
    _c("侍立", "cat-behavior-daily"),
    _c("回首", "cat-behavior-daily", "回首而顾"),
    _c("手前伸", "cat-behavior-daily"),
    _c("拊膺", "cat-behavior-daily"),
    _c("卧地举舞", "cat-behavior-daily", "", "老莱子娱亲格套中作婴儿之态。"),
    _c("执剑", "cat-behavior-combat"),
    _c("荷戟", "cat-behavior-combat"),
    _c("劫刺", "cat-behavior-combat", "行刺"),
    _c("惊避", "cat-behavior-combat"),
    _c("驾车", "cat-behavior-travel", "御车"),
    _c("骑马", "cat-behavior-travel"),
    _c("织布", "cat-behavior-labor", "坐织机"),
    _c("耕作", "cat-behavior-labor", "辟土"),
    _c("捧鱼进献", "cat-behavior-labor", "进献"),
    _c("捣药", "cat-behavior-labor"),
]
